module.exports = {
	CARD_CONTRACT: '0x76be3b62873462d2142405439777e971754e8e77',
	PARALLEL_COLORS: {
		'Augencore': 0xF26D15,
		'Marcolian': 0xEE0D0D,
		'Kathari': 0x146CCA,
		'Shroud': 0x6D15F2,
		'Earthen': 0x2CD823,
		'Universal': 0xFFFFFF,
	},
	PS15: [
		"Synchronicity [SE]",
		"Archivist's Pride [SE]",
		"Recon [SE]",
		"Revitalizing Growth [SE]",
		"Graphene Batteries [SE]",
		"Aurora Fungi [SE]",
		"Orbital Strike [SE]",
		"Ashes to Ashes [SE]",
		"Cytokinesis [SE]",
		"Artillery Volley [SE]",
		"Gaffar's Peace Pipe [SE]",
		"Kethtrexamine [SE]",
		"Neutron Bomb [SE]",
		"First Son of Mars [SE]",
		"The Priming",
		"Prime Key",
		"Catalyst Drive",
		"Galaxy Key",
	],
}
